n1 = int(input('Digite um número: '))
n2 = int(input('Digite outro número menor que o primeiro: '))
print('Com esses 2 numeros soma é: ', n1 + n2)
print('Com esses 2 numeros subtração é: ', n1 - n2)
print('Com esses 2 numeros a divisao é: ', n1 / n2)
print('Com esses 2 numeros multiplicação é: ', n1 * n2)
print('Um nº elevado ao outro é: ', n1 ** n2)
print('Com esses 2 numeros o resultado da divisão inteira é: ', n1 // n2)
print('Com esses 2 numeros o modulo é: ', n1 % n2)