nome = input('Qual o seu nome? ')
print('Bem vindo(a) {:20}!' .format(nome))
print('Bem vindo(a) {:>20}!' .format(nome))
print('Bem vindo(a) {:<20}!' .format(nome))
print('Bem vindo(a) {:=^20}!' .format(nome))
print('Bem vindo(a) {:^20}!' .format(nome))
print('Bem vin\ndo(a) {}!' .format(nome*5))
n = int(input('Um número: '))
print('Esse numero /2 é {:.5f}'.format(n/2))
